// Shared React-PDF stylesheet. Every document uses these base styles for
// page chrome, headers, tables, and totals. Per-template stylesheets can
// extend; avoid forking the basics so PDFs stay consistent.

import { StyleSheet } from "@react-pdf/renderer";
import { BRANDING } from "./branding";

export const sharedStyles = StyleSheet.create({
  page: {
    paddingTop: 48,
    paddingBottom: 64,
    paddingHorizontal: 48,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: BRANDING.textColor,
    backgroundColor: "#ffffff",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 24,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: BRANDING.textColor,
  },
  brandBlock: { flexDirection: "column" },
  brandName: { fontSize: 16, fontWeight: 700 },
  brandLine: { fontSize: 9, color: BRANDING.mutedColor, marginTop: 2 },
  docTitle: { fontSize: 20, fontWeight: 700, textAlign: "right" },
  docMeta: { fontSize: 9, color: BRANDING.mutedColor, marginTop: 4, textAlign: "right" },
  sectionTitle: {
    fontSize: 9,
    fontWeight: 700,
    color: BRANDING.mutedColor,
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 4,
    marginTop: 12,
  },
  twoCol: { flexDirection: "row", justifyContent: "space-between" },
  blockLabel: { fontSize: 9, color: BRANDING.mutedColor },
  blockValue: { fontSize: 11, marginTop: 2 },
  table: { marginTop: 12, borderWidth: 1, borderColor: BRANDING.textColor },
  tableRow: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: BRANDING.textColor },
  tableRowLast: { flexDirection: "row" },
  tableHeader: { backgroundColor: "#eeeeee", fontWeight: 700 },
  tableCell: { paddingVertical: 6, paddingHorizontal: 8, fontSize: 10 },
  cellLeft: { textAlign: "left" },
  cellRight: { textAlign: "right" },
  totals: { marginTop: 16, alignSelf: "flex-end", width: 220 },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 3,
    fontSize: 11,
  },
  grandTotalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 6,
    marginTop: 4,
    borderTopWidth: 2,
    borderTopColor: BRANDING.textColor,
    fontWeight: 700,
    fontSize: 13,
  },
  footer: {
    position: "absolute",
    bottom: 32,
    left: 48,
    right: 48,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 8,
    color: BRANDING.mutedColor,
    borderTopWidth: 1,
    borderTopColor: "#cccccc",
    paddingTop: 8,
  },
  watermark: {
    position: "absolute",
    top: "45%",
    left: 0,
    right: 0,
    textAlign: "center",
    fontSize: 80,
    color: "#fde8c8",
    fontWeight: 700,
    transform: "rotate(-25deg)",
  },
});
